# Sevalla Static Web Configuration for React Frontend
# This file documents the static hosting configuration

# Site Details
name: dispo-rusty-fe
branch: main  # or 'dev' depending on your workflow

# Build Configuration
root_directory: frontend
build_command: npm run build
node_version: 20  # or latest LTS
publish_directory: dist

# Routing Configuration
index_file: index.html
error_file: index.html  # For SPA routing (404s redirect to index.html)

# Environment Variables (set these in Sevalla dashboard)
# VITE_API_BASE_URL: https://your-backend-api.kinsta.app/api
# VITE_APP_NAME: Dispo Rusty
# NODE_ENV: production

# Headers (Optional - configure in Sevalla dashboard if needed)
# For CORS and security headers
headers:
  - path: "/*"
    headers:
      - key: "X-Frame-Options"
        value: "DENY"
      - key: "X-Content-Type-Options"
        value: "nosniff"
      - key: "Referrer-Policy"
        value: "strict-origin-when-cross-origin"
      - key: "Permissions-Policy"
        value: "camera=(), microphone=(), geolocation=()"

# Redirects for SPA (Single Page Application)
# All routes should redirect to index.html
redirects:
  - from: "/*"
    to: "/index.html"
    status: 200  # Rewrite (not redirect) for SPA routing
    conditions:
      - "!file"  # Only if file doesn't exist
