[phases.setup]
nixPkgs = [
  "pkg-config",
  "openssl",
  "postgresql",
  "rustup",
  "gcc",
  "gnumake",
  "cmake"
]

[phases.install]
cmds = [
  "rustup toolchain install stable --profile minimal",
  "rustup default stable",
  "cargo fetch"
]

[phases.build]
cmds = [
  "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$(find /nix/store -name libpq.pc -type f | head -1 | xargs dirname) && cargo build --release --bin rcs"
]
cacheDirectories = [
  "target"
]

[start]
cmd = "APP_HOST=0.0.0.0 APP_PORT=${PORT:-8000} ./target/release/rcs"
