CREATE TABLE tenants (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  db_url TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
